jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    com:
      a105:
        kurento: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 347493483528-h0eb923lqrqe12a39b1a044c6r0rjcik.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          naver:
            client-id: LEj86kXb7NOQ3MK3z7x0
            client-secret: ua1tiYD5Tr
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          #            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: b045f7299f24b09cfad7a21c8cd91ef6
            client-secret: AU3XmTowoE1VBoCqFK8YDWxtq4ctnTrO
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        #            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 유저 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

cloud:
  aws:
    credentials:
      access-key: AKIA2NWJP6PSREIKKF66
      secret-key: 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
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false
    s3:
      bucket: meeteat-bucket

#local환경
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/a105?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

#aws환경
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/a105?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin