spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/a105?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 347493483528-h0eb923lqrqe12a39b1a044c6r0rjcik.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: LEj86kXb7NOQ3MK3z7x0
            client-secret: ua1tiYD5Tr
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 유저 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌



logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG