jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    com:
      a105:
        kurento: DEBUG

oauth2:
  provider:
    google:
      client-id: 347493483528-h0eb923lqrqe12a39b1a044c6r0rjcik.apps.googleusercontent.com
      client-secret: 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
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
    kakao:
      client-id: b045f7299f24b09cfad7a21c8cd91ef6
      client-secret: AU3XmTowoE1VBoCqFK8YDWxtq4ctnTrO
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
    naver:
      client-id: LEj86kXb7NOQ3MK3z7x0
      client-secret: ua1tiYD5Tr
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me

jwt:
  secret-key: A1$0$5MeetEat-hayunA1$0$5MeetEat-hayunA1$0$5MeetEat-hayun
  access-token:
    expiry: 864000000
  refresh-token:
    expiry: 864000000

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

cloud:
  aws:
    instance:
      data:
        enabled:
          - false
    credentials:
      access-key: AKIA2NWJP6PSU63KCJPL
      secret-key: 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
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false
    s3:
      bucket: meeteat-bucket
    cloudfront:
      domain: https://d2ju23e8zeqnl1.cloudfront.net/



#local환경
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/a105?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

#aws환경
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/a105?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin